version: '3.8'

services:
  mongo-secondary1:
    image: mongo:7.0
    container_name: mongo-secondary1
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    command: mongod --replSet rs0 --port 27017 --bind_ip_all
    volumes:
      - mongo_secondary1_data:/data/db
    networks:
      - mongo-network

volumes:
  mongo_secondary1_data:

networks:
  mongo-network:
    driver: bridge
